### ISSUE TITLE
I ran "Adeleine" and got an error.

### ISSUE THREAD

**Issue by Foresiver5555** [SerialLain3170/Colorization#21]
Excuse me.
When I used "Adeleine" to color the reference_scft model that I learned the other day, I got the following error message when uploading the line drawing
```
Traceback (most recent call last):
  File "/home/dbl/.local/lib/python3.6/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dbl/.local/lib/python3.6/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dbl/.local/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dbl/.local/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dbl/.local/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dbl/.local/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/data/Colorization-master/Adeleine/server.py", line 92, in ref_upload
    line, h, w = base64decode(request.json['image'], limit=ref_base)
  File "/data/Colorization-master/Adeleine/server.py", line 54, in base64decode
    img, h, w = resize(img, limit)
  File "/data/Colorization-master/Adeleine/server.py", line 30, in resize
    h, w = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
```
I got an error message "I can't upload an image.
The uploaded image is a 512*512 image for both the line drawing and the reference image.

The other changes I made were that I hadn't learned "atari", "flatten", and "point" yet, and I wanted to try coloring the reference image first.
```
    #atari_infer = AtariInferer("./atari/model_136001.pt")
    #flat_infer = FlatInferer("./flatten/flat_158001.pt")
    #point_infer = PointInferer("./point/generator_570001.pt")
```
I got the above error and could not upload the image.
The uploaded image is a 512*512 image for both the line drawing and the reference image.

I apologize for the amateur question, but if you have a solution, please let me know.

Also, I asked the question in Japanese because it sounds Japanese, but I will ask it again if English is better.

**Comment by SerialLain3170** [comment]
I am sorry for the inconvenience.

Temporarily, I think that converting `.jpg` , which is a suffix of your image file, into `.png` would work.

**Comment by Foresiver5555** [comment]
Thank you, I was able to upload a png.

One more question, do you plan to upload the 4 pre-trained models "reference", "atari", "flatten" and "point"?

**Comment by SerialLain3170** [comment]
That was good. Since the application must accept not only `.png` but also `.jpg`, I should tackle the problem. Thank you for the report.

I do not plan to upload all of the pre-trained files, but I plan to do one of them.

**Comment by SerialLain3170** [comment]
Moreover, please write an issue in English from next time so that those who watch the repository can read the issues.
