### ISSUE TITLE
Is there any reference or flatten pretrained weights available?

### ISSUE THREAD

**Issue by JunweiSUN** [SerialLain3170/Colorization#25]
Hi there,

Thanks for this great work! Just wonder is there any reference or flatten pretrained weights available since I only see a point model in the tag. By the way, I got a shape mismatch error when using the point model (with Adeleine GUI):

```
127.0.0.1 - - [21/Jan/2022 00:33:22] "POST /point HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\HomePC\Desktop\Colorization\Adeleine\server.py", line 174, in point
    y = point_infer(line, point, place)
  File "C:\Users\HomePC\Desktop\Colorization\Adeleine\point\inference.py", line 91, in __call__
    y, _, _ = self.model(x, line_m)
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\HomePC\Desktop\Colorization\Adeleine\point\model.py", line 708, in forward
    ce, mid_layer_list = self.ce(x)
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\HomePC\Desktop\Colorization\Adeleine\point\model.py", line 530, in forward
    x = layer(x)
  File "C:\Users\HomePC\AppData\Local\Programs\DeepLearningStudio\program_data\programs\conda\envs\torch\Lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\HomePC\Desktop\Colorization\Adeleine\point\model.py", line 299, in forward
    return x + skip
RuntimeError: The size of tensor a (234) must match the size of tensor b (235) at non-singleton dimension 2
```

Here is the png I use:
![test2](https://user-images.githubusercontent.com/30487595/150382556-4c44d08f-297c-441e-ac1f-9352b7494337.png)

Is there any easy work around?

Looking forward to your reply, and thanks for this repo again!

**Comment by SerialLain3170** [comment]
There are no pretrained models for reference and flatten now. I do not plan to upload these pretrained files at present.

When it comes to the size mismatch error, the error comes from the limited shape that the point model can accept. At present, the point model can accept only shapes that are two to the Nth power (ex: 256, 512, 1024, etc). So, tentatively, you need to resize your images. I am sorry for the inconvenience.

**Comment by JunweiSUN** [comment]
> There are no pretrained models for reference and flatten now. I do not plan to upload these pretrained files at present.
> 
> When it comes to the size mismatch error, the error comes from the limited shape that the point model can accept. At present, the point model can accept only shapes that are two to the Nth power (ex: 256, 512, 1024, etc). So, tentatively, you need to resize your images. I am sorry for the inconvenience.

Got it. Thanks a lot for your rapid reply!
