### ISSUE TITLE
Which datasets were used for this project?

### ISSUE THREAD

**Issue by FoolishBrown** [SerialLain3170/Colorization#8]
Your works are  greatly helpful to me,
Thanks agian!

**Comment by SerialLain3170** [comment]
Thanks! I have mainly used [Tagged Anime illustrations](https://www.kaggle.com/mylesoneill/tagged-anime-illustrations) in Kaggle except for `nohint_bicyclegan` whose results are based on [danbooru face dataset](https://github.com/stormraiser/adversarial-disentangle#dataset).  After downloading these datasets, I extracted line arts with SketchKeras or Sketch simplification.  

I think [Anime Sketch Colorization Pair](https://www.kaggle.com/ktaebum/anime-sketch-colorization-pair) in Kaggle may be also helpful.

**Comment by FoolishBrown** [comment]
I have a problem and maybe you can help me:  when I install the env for chainer,  I got the error like this "cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed". I've tried a lot of version(eg. 6.1.0 7.1.0 7.7.0...)
Below I give detils,

- Env:
CentOS RedHat 7.5
python 3.7
cuda 9.0
cupy cupy-cuda90-7.8
chainer 7.7
- Error msg:
 Traceback (most recent call last):
  File "/home/skj/IDE/pycharm-2018.2.5/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/skj/IDE/pycharm-2018.2.5/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/skj/IDE/pycharm-2018.2.5/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/skj/IDE/pycharm-2018.2.5/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/skj/Git_Project/Colorization/atari_userhint/train.py", line 320, in <module>
    args.sn, args.bn, args.act)
  File "/home/skj/Git_Project/Colorization/atari_userhint/train.py", line 88, in train
    color_valid, line_valid, mask_valid, ds_valid = dataloader(validsize, mode="valid")
  File "/home/skj/Git_Project/Colorization/atari_userhint/dataset.py", line 297, in __call__
    color = self._variable(color_box)
  File "/home/skj/Git_Project/Colorization/atari_userhint/dataset.py", line 172, in _variable
    data = xp.array(image_list).astype(xp.float32)
  File "cupy/core/core.pyx", line 318, in cupy.core.core.ndarray.astype
  File "cupy/core/core.pyx", line 389, in cupy.core.core.ndarray.astype
  File "cupy/core/_kernel.pyx", line 856, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 868, in cupy.core._kernel.ufunc._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 630, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 166, in cupy.core.core.compile_with_cache
  File "/home/skj/anaconda3/envs/chainer/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 167, in compile_with_cache
    ls.add_ptr_data(ptx, u'cupy.ptx')
  File "cupy/cuda/function.pyx", line 212, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/function.pyx", line 214, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/driver.pyx", line 153, in cupy.cuda.driver.linkAddData
  File "cupy/cuda/driver.pyx", line 82, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed

**Comment by FoolishBrown** [comment]
I sovled this problem by uninstall cupy-cuda90 & install cupy(The official website guides me to install cupy-cuda90..  I still have no idea for the BUG)
...

**Comment by SerialLain3170** [comment]
I'm glad that you resolved the problem that was related to installation of cupy. I also have no idea for the bug.
